spring:
  application:
    name: datalabel
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/datalabel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 로컬에서는 엔티티 변경에 맞춰 DB 테이블을 자동 수정합니다.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # N+1 문제 해결을 위한 핵심 최적화 옵션 (면접 어필 포인트!)

  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  # 실무에서는 환경변수(${JWT_SECRET})로 주입받아야 하지만, 로컬 개발을 위해 하드코딩합니다.
  secret: ZGF0YWxhYmVsLXBvcnRmb2xpby1qd3Qtc2VjcmV0LWtleS1tdXN0LWJlLWxvbmctZW5vdWdo
  access-token-validity-in-milliseconds: 3600000 # 1시간 (1000 * 60 * 60)
